### ISSUE TITLE
Edge rendering

### ISSUE THREAD

**Issue by tpaviot** [andreasplesch/OCCToX3D#1]
Currently, at pythonocc, there's an option to export edges into the .x3d file for a shape. This makes rendering much better, for instance with edge rendering enabled we have:

![cylinder_edge_with_edges_x3dom](https://user-images.githubusercontent.com/660130/80186659-a38fdd00-860e-11ea-962c-d2db4df01a52.png)

and without (the poor cylinder head seems to be naked)
![cylinder_edge_without_edges_x3dom](https://user-images.githubusercontent.com/660130/80186572-7d6a3d00-860e-11ea-82f0-869434ffa099.png)

Rendering edges brings a real benefit to the visualization, however the current edge representation  in x3dom is not optimal (the way we do it of course, not x3dom by itself): edges are discretized and exported to a ```LineSet``` representation, each ```LineSet``` being inserted into a new ```<Shape>```. Then, for a single box with 6 faces and 8 vertices and 12 edges, this results in an x3d file including 13 ```Shapes``` (1 for the solid description, 12 for the edges). As far as I understand, a high number of shapes is not good for rendering performance.

The current file structure looks like that
```bash
<Transform scale="1 1 1">
        <Shape DEF="edg6">
	<Appearance><Material emissiveColor="0 0 0" /></Appearance>
	<LineSet vertexCount="2"><Coordinate point="10 20 10 10 20 40 " /></LineSet>
	</Shape></Transform>
	<Transform scale="1 1 1"><Shape DEF="edg7">
	<Appearance><Material emissiveColor="0 0 0" /></Appearance>
	<LineSet vertexCount="2"><Coordinate point="10 0 10 10 20 10 " /></LineSet>
	</Shape></Transform>
	<Transform scale="1 1 1"><Shape DEF="edg8">
			<Appearance><Material emissiveColor="0 0 0" /></Appearance>
			<LineSet vertexCount="2"><Coordinate point="0 0 10 10 0 10 " /></LineSet>
		</Shape></Transform>
```
I would like all these line to belong to the same Shape, and rather have something like that:
```
<Transform scale="1 1 1">
        <Shape DEF="all_edges">
	<Appearance><Material emissiveColor="0 0 0" /></Appearance>
	<LineSet vertexCount="2"><Coordinate point="10 20 10 10 20 40 " /></LineSet>
	<LineSet vertexCount="2"><Coordinate point="10 0 10 10 20 10 " /></LineSet>
	<LineSet vertexCount="2"><Coordinate point="0 0 10 10 0 10 " /></LineSet>
         [...]
	</Shape></Transform>
```
but, in this case, only the first LineSetis rendered.

So the question: is it possible to insert and render many different ```LineSet``` into a single ```Shape``` ? Otherwise do I have to change the line representation ?

**Comment by andreasplesch** [comment]
Thanks for pythonocc and your hard work getting it functioning so well !

Yes, you can combine the edges into a single Shape, using LineSet or using IndexedLineSet. Here are examples:

https://x3dgraphics.com/examples/X3dForWebAuthors/Chapter06GeometryPointsLinesPolygons/LineSetComparisonIndex.html

Note the vertexCount field of LineSet. It can have multiple entries, each one defining a separate line. 

So the three LineSets in your example would become:

```
<LinesSet vertexCount='2 2 2' point='10 20 10, 10 20 40, 10 0 10, 10 20 10, 0 0 10, 10 0 10' />
```
[ Segments are connected, so I think you could optimize that to:]
```
<LinesSet vertexCount='4' point='0 0 10, 10 0 10, 10 20 10, 10 20 40 ' />
```

IndexedLineSet is an option as well, but since points are rarely used by multiple segments, it does not provide size benefits. But it may better fit the TopoShp data structure and be easier to construct. The three LineSets would become:

```
<IndexedLineSet coordIndex='0 1 -1 2 0 -1 3 2 -1'>
  <Coordinate point='10 20 10, 10 20 40, 10 0 10, 0 0 10''/>
</IndexedLineSet>
```

**Comment by tpaviot** [comment]
Thank you, that makes my day. Are the commas necessary in the Coordinate list ?

**Comment by andreasplesch** [comment]
no the commas are not necessary.

**Comment by tpaviot** [comment]
This is a WIP at pythonocc-core, I'll report any success/failure

**Comment by andreasplesch** [comment]
thanks
